### ISSUE TITLE
TypeError INTERNAL problem after upgrade from 10.0.1 to 20.6.0

### ISSUE THREAD

**Issue by qwsj** [getsentry/onpremise#818]
### Version Information

Version: 20.6.0

### Steps to Reproduce

1. Upgrade onpremise from 10.0.1 to 20.6.0
2. Click to link "Activity", "Issues" or "Stats"

### Expected Result

Page is loaded without problem, but have INTERNAL error

### Actual Result
```
TypeError /organizations/:orgId/activity/
r.takeRecords is not a function. (In 'r.takeRecords()', 'r.takeRecords' is undefined)
TypeError: r.takeRecords is not a function. (In 'r.takeRecords()', 'r.takeRecords' is undefined)
  at ? (/workspace/node_modules/@sentry/apm/esm/integrations/tracing.js:491:26)
  at endTimestamp(/workspace/node_modules/@sentry/apm/esm/integrations/tracing.js:352:13)
  at getSpan(/workspace/node_modules/@sentry/apm/esm/integrations/tracing.js:280:31)
  at apply(/workspace/node_modules/@sentry/apm/esm/integrations/tracing.js:155:27)
  at ignoreOnError(/workspace/node_modules/@sentry/browser/esm/helpers.js:71:23)
```

```
TypeError /organizations/:orgId/issues/
r.takeRecords is not a function. (In 'r.takeRecords()', 'r.takeRecords' is undefined)
TypeError: r.takeRecords is not a function. (In 'r.takeRecords()', 'r.takeRecords' is undefined)
  at ? (/_static/1610715505/sentry/dist/vendor.js:102:50784)
  at ? (/_static/1610715505/sentry/dist/vendor.js:102:48452)
  at ? (/_static/1610715505/sentry/dist/vendor.js:102:47746)
  at ? (/_static/1610715505/sentry/dist/vendor.js:102:46027)
  at a(/_static/1610715505/sentry/dist/vendor.js:65:103509)
```

```
TypeError /organizations/:orgId/stats/
r.takeRecords is not a function. (In 'r.takeRecords()', 'r.takeRecords' is undefined)
TypeError: r.takeRecords is not a function. (In 'r.takeRecords()', 'r.takeRecords' is undefined)
  at ? (/_static/1610715505/sentry/dist/vendor.js:102:50784)
  at ? (/_static/1610715505/sentry/dist/vendor.js:102:48452)
  at ? (/_static/1610715505/sentry/dist/vendor.js:102:47746)
  at ? (/_static/1610715505/sentry/dist/vendor.js:102:45536)
  at ? (/_static/1610715505/sentry/dist/vendor.js:102:45019)
  at a(/_static/1610715505/sentry/dist/vendor.js:65:103509)
```

![sentry-internal-error](https://user-images.githubusercontent.com/10673437/104734023-46156080-5748-11eb-83bd-ff981c449ff3.png)

### Logs

There is no problem in the logs

**Comment by qwsj** [comment]
let me know if need to recreate this issue in the getsentry/sentry repository

**Comment by BYK** [comment]
Can you try upgrading to the latest version first as 20.6.0 is quite old.

**Comment by qwsj** [comment]
@BYK after upgrade from 10.0.1 to 20.11.1 no any problems. Thanks for help. Im close this issue.
